a=[1,2,3]
del(a[1])
print(a)
num=[1,2,3,5]
print(max(num))
print(min(num))
str="abcz"
print(max(str))
print(min(str))
print(num*2)
tup=(1,2)
print(tup*5)
print(str*2)
print("hello"+"python")
print([1,2]+["a"])
print((1,2)+(3,))
num.extend([6,7])
print(num)
num.append([6,7])
print(num)
print("a" in "abc")
print("a" not in "abc")
print("a" in {"a":"b"})
print("b" in {"a":"b"})
